# Generated by Django 4.0.5 on 2022-06-21 15:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('course_duration', model_utils.fields.StatusField(choices=[('30 daqiqa', '30 daqiqa'), ('40 daqiqa', '40 daqiqa'), ('60 daqiqa', '60 daqiqa'), ('90 daqiqa', '90 daqiqa'), ('120 daqiqa', '120 daqiqa'), ('180 daqiqa', '180 daqiqa'), ('240 daqiqa', '240 daqiqa'), ('280 daqiqa', '280 daqiqa'), ('300 daqiqa', '300 daqiqa')], default='30 daqiqa', max_length=100, no_check_for_status=True)),
                ('cost', models.FloatField(default=0)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15)),
                ('birth_day', models.DateField()),
                ('gender', model_utils.fields.StatusField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, no_check_for_status=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='xodim/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson_time', models.TimeField()),
                ('beginning_date', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.course')),
                ('days', models.ManyToManyField(to='markaz.day')),
            ],
        ),
        migrations.CreateModel(
            name='Harajatturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IshHaqqiTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('oluvchi', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('xarajat_turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.harajatturi')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20)),
                ('birth_day', models.DateField()),
                ('gender', model_utils.fields.StatusField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, no_check_for_status=True)),
                ('bio', models.TextField()),
                ('come_date', models.DateField(auto_now_add=True)),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', model_utils.fields.StatusField(choices=[('Naqt pul', 'Naqt pul'), ('UZCARD', 'UZCARD'), ('Bank hisobi', 'Bank hisobi')], default='Naqt pul', max_length=100, no_check_for_status=True)),
                ('quantity', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.student')),
            ],
        ),
        migrations.CreateModel(
            name='IshHaqqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField()),
                ('cource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.course')),
                ('ish_haqqi_turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.ishhaqqituri')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.room'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markaz.roll'),
        ),
    ]
