# Generated by Django 4.0.5 on 2022-06-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
    ]
