from .course import *
from .day import *
from .guruh import *
from .harajatturi import *
from .ish_haqqi import *
from .ish_haqqi_turi import *
from .payment import *
from .roll import *
from .room import *
from .student import *
from .xarajat import *
from .xodim import *